name: UUP dump using GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/windows/server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip last modified zip file
        run: |
          latest_zip=$(Get-ChildItem -Path . -Filter *.zip | Sort-Object LastWriteTime | Select-Object -Last 1)
          Expand-Archive -Path $latest_zip.FullName -DestinationPath extracted

      - name: Create ISO using UUP dump
        run: ./extracted/uup_download_windows.cmd

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: extracted/*.ISO
